In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score,precision_score,f1_score,classification_report
from sklearn.preprocessing import LabelEncoder

In [12]:
df=pd.read_csv("iris.csv")
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [18]:
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [24]:
x=df.drop('Species',axis=1)
y=df['Species']

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

In [36]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred))

print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred),columns=list(range(0,3)))

Accuracy of Logistic Regression 0.9777777777777777
Logistic Regression Confusion Matrix

    0   1   2
0  17   0   0
1   0  15   1
2   0   0  12

In [38]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred1=dt.predict(x_test)
print(accuracy_score(y_test,y_pred1))

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3)))

0.9555555555555556
Decision Tree Confusion Matrix

    0   1   2
0  17   0   0
1   0  15   1
2   0   1  11

In [42]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred
result['Decision Tree Prediction'] = y_pred1
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
40              0                               0                         0
113             2                               2                         2
31              0                               0                         0
127             2                               2                         2
79              1                               1                         1
122             2                               2                         2
135             2                               2                         2
93              1                               1                         1
25              0                               0                         0
99              1                               1                         1

In [44]:
precision_score(y_test,y_pred,average=None)

array([1.        , 1.        , 0.92307692])

In [46]:
recall_score(y_test,y_pred,average=None)

array([1.    , 0.9375, 1.    ])

In [48]:
precision_score(y_test,y_pred1,average='weighted')

0.9555555555555556

In [50]:
recall_score(y_test,y_pred1,average='weighted')

0.9555555555555556

In [53]:
f1_score(y_test,y_pred1,average='weighted')

0.9555555555555556

In [59]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.94      0.94      0.94        16
           2       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45